name: Semigroups
version: 3.0.17
date: 2018-08-23
description: |
    A package for semigroups and monoids

authors:
    - name: J. D. Mitchell
      url: http://www-groups.mcs.st-andrews.ac.uk/~jamesm/

maintainers:
    - name: J. D. Mitchell
      url: http://www-groups.mcs.st-andrews.ac.uk/~jamesm/

contributors:
    - name: S. Burrell
      url: http://sburrell.nfshost.com
    - name: M. Delgado
      url: http://cmup.fc.up.pt/cmup/mdelgado/
    - name: J. East
      url: http://goo.gl/MuiJu5
    - name: A. Egri-Nagy
      url: http://www.egri-nagy.hu
    - name: N. Ham
      url: https://n-ham.github.io
    - name: J. Jonusas
      url: http://www-groups.mcs.st-andrews.ac.uk/~julius/
    - name: M. Pfeiffer
      url: https://www.morphism.de/~markusp/
    - name: C. Russell
      url: mailto:cr66@st-andrews.ac.uk
    - name: B. Steinberg
      url: http://www.sci.ccny.cuny.edu/~benjamin/
    - name: F. Smith
      url: mailto:fls3@st-andrews.ac.uk
    - name: J. Smith
      url: http://math.sci.ccny.cuny.edu/people?name=Jhevon_Smith
    - name: M. Torpey
      url: http://www-groups.mcs.st-and.ac.uk/~mct25/
    - name: W. A. Wilson
      url: http://wilf.me

GAP: ">=4.9.0"

needed-pkgs:
    - name: "orb"
      version: ">=4.8.0"
      url: "https://gap-packages.github.io/orb"
    - name: "io"
      version: ">=4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "digraphs"
      version: ">=0.12.0"
      url: "https://gap-packages.github.io/Digraphs"
    - name: "genss"
      version: ">=1.6.5"
      url: "https://gap-packages.github.io/genss"

suggested-pkgs:
    - name: "gapdoc"
      version: ">=1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/Semigroups
readme: README.md
packageinfo: https://gap-packages.github.io/Semigroups/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/Semigroups/releases/download/v3.0.17/semigroups-3.0.17.tar.gz

abstract: |
    <p>The Semigroups package is a GAP package containing methods for semigroups, monoids, and inverse semigroups.  There are particularly efficient methods for semigroups or ideals consisting of transformations, partial permutations, bipartitions, partitioned binary relations, subsemigroups of regular Rees 0-matrix semigroups, and matrices of various semirings including boolean matrices, matrices over finite fields, and certain tropical matrices.</p><p>Semigroups contains efficient methods for creating semigroups, monoids, and inverse semigroup, calculating their Green's structure, ideals, size, elements, group of units, small generating sets, testing membership, finding the inverses of a regular element, factorizing elements over the generators, and so on. It is possible to test if a semigroup satisfies a particular property, such as if it is regular, simple, inverse, completely regular, and a variety of further properties.</p><p>There are methods for finding presentations for a semigroup, the congruences of a semigroup, the normalizer of a semigroup in a permutation group, the maximal subsemigroups of a finite semigroup, smaller degree partial permutation representations, and the character tables of inverse semigroups. There are functions for producing pictures of the Green's structure of a semigroup, and for drawing graphical representations of certain types of elements.</p>

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
